name: midterm_app
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  intl: ^0.17.0
  flutter_spinkit: ^5.1.0
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/winai.png"
  

flutter:
  uses-material-design: true
  assets:
    - assets/winai.jpg
    - assets/winai.png
    - assets/chanel.png
    - assets/may.png
    - assets/ron.png
    - assets/tang.png
    - assets/bonus.png
    - assets/gift.jpg
    

